// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/admin.proto

package admin

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeleteDataRequest struct {
	TenantId             string   `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDataRequest) Reset()         { *m = DeleteDataRequest{} }
func (m *DeleteDataRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDataRequest) ProtoMessage()    {}
func (*DeleteDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92c9b71229522f37, []int{0}
}

func (m *DeleteDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDataRequest.Unmarshal(m, b)
}
func (m *DeleteDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDataRequest.Marshal(b, m, deterministic)
}
func (m *DeleteDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDataRequest.Merge(m, src)
}
func (m *DeleteDataRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDataRequest.Size(m)
}
func (m *DeleteDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDataRequest proto.InternalMessageInfo

func (m *DeleteDataRequest) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

type DeleteDataResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDataResponse) Reset()         { *m = DeleteDataResponse{} }
func (m *DeleteDataResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteDataResponse) ProtoMessage()    {}
func (*DeleteDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92c9b71229522f37, []int{1}
}

func (m *DeleteDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDataResponse.Unmarshal(m, b)
}
func (m *DeleteDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDataResponse.Marshal(b, m, deterministic)
}
func (m *DeleteDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDataResponse.Merge(m, src)
}
func (m *DeleteDataResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteDataResponse.Size(m)
}
func (m *DeleteDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDataResponse proto.InternalMessageInfo

type UsageRequest struct {
	TenantId             string   `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsageRequest) Reset()         { *m = UsageRequest{} }
func (m *UsageRequest) String() string { return proto.CompactTextString(m) }
func (*UsageRequest) ProtoMessage()    {}
func (*UsageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92c9b71229522f37, []int{2}
}

func (m *UsageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsageRequest.Unmarshal(m, b)
}
func (m *UsageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsageRequest.Marshal(b, m, deterministic)
}
func (m *UsageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsageRequest.Merge(m, src)
}
func (m *UsageRequest) XXX_Size() int {
	return xxx_messageInfo_UsageRequest.Size(m)
}
func (m *UsageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsageRequest proto.InternalMessageInfo

func (m *UsageRequest) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

type UsageResponse struct {
	Usage                map[string]*Usage `protobuf:"bytes,1,rep,name=usage,proto3" json:"usage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UsageResponse) Reset()         { *m = UsageResponse{} }
func (m *UsageResponse) String() string { return proto.CompactTextString(m) }
func (*UsageResponse) ProtoMessage()    {}
func (*UsageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92c9b71229522f37, []int{3}
}

func (m *UsageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsageResponse.Unmarshal(m, b)
}
func (m *UsageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsageResponse.Marshal(b, m, deterministic)
}
func (m *UsageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsageResponse.Merge(m, src)
}
func (m *UsageResponse) XXX_Size() int {
	return xxx_messageInfo_UsageResponse.Size(m)
}
func (m *UsageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsageResponse proto.InternalMessageInfo

func (m *UsageResponse) GetUsage() map[string]*Usage {
	if m != nil {
		return m.Usage
	}
	return nil
}

type Usage struct {
	Usage                int64    `protobuf:"varint,1,opt,name=usage,proto3" json:"usage,omitempty"`
	Units                string   `protobuf:"bytes,2,opt,name=units,proto3" json:"units,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Usage) Reset()         { *m = Usage{} }
func (m *Usage) String() string { return proto.CompactTextString(m) }
func (*Usage) ProtoMessage()    {}
func (*Usage) Descriptor() ([]byte, []int) {
	return fileDescriptor_92c9b71229522f37, []int{4}
}

func (m *Usage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Usage.Unmarshal(m, b)
}
func (m *Usage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Usage.Marshal(b, m, deterministic)
}
func (m *Usage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Usage.Merge(m, src)
}
func (m *Usage) XXX_Size() int {
	return xxx_messageInfo_Usage.Size(m)
}
func (m *Usage) XXX_DiscardUnknown() {
	xxx_messageInfo_Usage.DiscardUnknown(m)
}

var xxx_messageInfo_Usage proto.InternalMessageInfo

func (m *Usage) GetUsage() int64 {
	if m != nil {
		return m.Usage
	}
	return 0
}

func (m *Usage) GetUnits() string {
	if m != nil {
		return m.Units
	}
	return ""
}

func init() {
	proto.RegisterType((*DeleteDataRequest)(nil), "admin.DeleteDataRequest")
	proto.RegisterType((*DeleteDataResponse)(nil), "admin.DeleteDataResponse")
	proto.RegisterType((*UsageRequest)(nil), "admin.UsageRequest")
	proto.RegisterType((*UsageResponse)(nil), "admin.UsageResponse")
	proto.RegisterMapType((map[string]*Usage)(nil), "admin.UsageResponse.UsageEntry")
	proto.RegisterType((*Usage)(nil), "admin.Usage")
}

func init() {
	proto.RegisterFile("proto/admin.proto", fileDescriptor_92c9b71229522f37)
}

var fileDescriptor_92c9b71229522f37 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0xed, 0x36, 0x44, 0xcc, 0xb4, 0x45, 0x3b, 0xe6, 0x10, 0xeb, 0xc1, 0xb0, 0xa7, 0x80, 0x90,
	0x4a, 0xaa, 0x20, 0x7a, 0x52, 0xab, 0xe0, 0x35, 0xe0, 0xc5, 0x8b, 0xac, 0x64, 0x90, 0x60, 0xdd,
	0xd4, 0xee, 0x46, 0xe8, 0xd5, 0x0f, 0xf0, 0x9b, 0x25, 0xbb, 0x2b, 0x31, 0xd8, 0x43, 0x6f, 0xf3,
	0xde, 0xbc, 0x79, 0x33, 0xfb, 0x16, 0xc6, 0xcb, 0x55, 0xa5, 0xab, 0xa9, 0x28, 0xde, 0x4b, 0x99,
	0x9a, 0x1a, 0x7d, 0x03, 0xf8, 0x29, 0x8c, 0xe7, 0xb4, 0x20, 0x4d, 0x73, 0xa1, 0x45, 0x4e, 0x1f,
	0x35, 0x29, 0x8d, 0x47, 0x10, 0x68, 0x92, 0x42, 0xea, 0xe7, 0xb2, 0x88, 0x58, 0xcc, 0x92, 0x20,
	0xdf, 0xb5, 0xc4, 0x43, 0xc1, 0x43, 0xc0, 0xbf, 0x13, 0x6a, 0x59, 0x49, 0x45, 0xfc, 0x04, 0x86,
	0x8f, 0x4a, 0xbc, 0xd2, 0x56, 0x16, 0xdf, 0x0c, 0x46, 0x4e, 0x6d, 0xc7, 0xf1, 0x1c, 0xfc, 0xba,
	0x21, 0x22, 0x16, 0x7b, 0xc9, 0x20, 0x3b, 0x4e, 0xed, 0xa9, 0x1d, 0x91, 0x45, 0x77, 0x52, 0xaf,
	0xd6, 0xb9, 0x55, 0x4f, 0xee, 0x01, 0x5a, 0x12, 0xf7, 0xc1, 0x7b, 0xa3, 0xb5, 0xdb, 0xd6, 0x94,
	0xc8, 0xc1, 0xff, 0x14, 0x8b, 0x9a, 0xa2, 0x7e, 0xcc, 0x92, 0x41, 0x36, 0xec, 0xd8, 0xda, 0xd6,
	0x65, 0xff, 0x82, 0xf1, 0x19, 0xf8, 0x86, 0xc3, 0xb0, 0xbd, 0x83, 0x25, 0x9e, 0x5b, 0x63, 0x58,
	0x59, 0x6a, 0x65, 0x6c, 0x82, 0xdc, 0x82, 0xec, 0x8b, 0x81, 0x7f, 0xdd, 0xf8, 0xe1, 0x2d, 0x40,
	0x1b, 0x09, 0x46, 0x6e, 0xcb, 0xbf, 0x5c, 0x27, 0x87, 0x1b, 0x3a, 0x2e, 0xbf, 0x1e, 0x9e, 0xfd,
	0xde, 0x70, 0xd0, 0x7d, 0xbc, 0x1d, 0x0d, 0x37, 0x25, 0xc2, 0x7b, 0x37, 0x7b, 0x4f, 0xa3, 0x74,
	0x6a, 0x7e, 0xf4, 0xca, 0x08, 0x5e, 0x76, 0x0c, 0x98, 0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0x10,
	0xe3, 0xf5, 0x28, 0xf3, 0x01, 0x00, 0x00,
}
